fixed the layout
nannyhub/NannysHub pull request #13
Opened 2022-03-18 19:57 UTC by MaiCodes-exe

2022-03-18 20:43 UTC, ertip4geek approved these changes

2022-03-18 20:52 UTC, ertip4geek commented
Maise sorry last thing, for your pending PR, could you make 1 more commit without the file package-lock.json.
Because is causing 12 conflicts and is doing errors to be resolvev, just skip that file will be ok
thanks!:

2022-03-19 13:26 UTC, vitortamberlini requested changes

2022-03-19 13:26 UTC, vitortamberlini commented on src/front/js/pages/contacts.js
> +            ></img>
<img> is a self-closing tag:
```suggestion
            <img
              src="https://images.pexels.com/photos/5691814/pexels-photo-5691814.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
              id="kids"
            />
```

2022-03-19 13:26 UTC, vitortamberlini commented on src/front/js/pages/contacts.js
> +              Later on, we were joined by another memember who, despite not
Typo:
```suggestion
              Later on, we were joined by another member who, despite not
```

2022-03-19 13:26 UTC, vitortamberlini commented on src/front/styles/contacts.css
> +#titulo {
nit: Change this id to `title` for consistency

2022-03-20 18:42 UTC, merged